version: '3'
services:
  web:
    image: wordpress:latest
    links:
    - mysql
    environment:
    - WORDPRESS_DB_PASSWORD=password
    ports:
    - "127.0.0.1:8080:80"
    volumes:
    - ./kyma:/var/www/html/wp-content/plugins/kyma
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=my-wpdb
